"""Inital table version

Revision ID: 7a41850282c5
Revises: 
Create Date: 2024-10-04 22:34:46.607558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a41850282c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_inventory',
    sa.Column('product_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('brand', sa.VARCHAR(length=64), nullable=True),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_unit', sa.VARCHAR(length=64), nullable=False),
    sa.Column('mfg_date', sa.VARCHAR(length=64), nullable=False),
    sa.Column('exp_date', sa.VARCHAR(length=64), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('buying_price', sa.FLOAT(), nullable=False),
    sa.Column('selling_price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    schema='public'
    )
    op.create_table('user_admin',
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='public'
    )
    op.create_table('user_buyer',
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='public'
    )
    op.create_table('user_inventory_manager',
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='public'
    )
    op.create_table('user_seller',
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='public'
    )
    op.create_table('buying_history',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_unit', sa.VARCHAR(length=64), nullable=False),
    sa.Column('buy_price', sa.FLOAT(), nullable=False),
    sa.Column('adv_payment', sa.FLOAT(), nullable=False),
    sa.Column('rest_payment', sa.FLOAT(), nullable=False),
    sa.Column('buy_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['public.trace_inventory.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user_buyer.user_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    schema='public'
    )
    op.create_table('selling_history',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_unit', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sold_price', sa.FLOAT(), nullable=False),
    sa.Column('adv_payment', sa.FLOAT(), nullable=False),
    sa.Column('rest_payment', sa.FLOAT(), nullable=False),
    sa.Column('sold_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['public.trace_inventory.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user_seller.user_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selling_history', schema='public')
    op.drop_table('buying_history', schema='public')
    op.drop_table('user_seller', schema='public')
    op.drop_table('user_inventory_manager', schema='public')
    op.drop_table('user_buyer', schema='public')
    op.drop_table('user_admin', schema='public')
    op.drop_table('trace_inventory', schema='public')
    # ### end Alembic commands ###
