"""changing column name from last_updated to updated_at

Revision ID: aca530597653
Revises: 7a41850282c5
Create Date: 2024-10-04 23:08:04.426380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aca530597653'
down_revision: Union[str, None] = '7a41850282c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('buying_history_user_id_fkey', 'buying_history', type_='foreignkey')
    op.drop_constraint('buying_history_product_id_fkey', 'buying_history', type_='foreignkey')
    op.create_foreign_key(None, 'buying_history', 'user_buyer', ['user_id'], ['user_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'buying_history', 'trace_inventory', ['product_id'], ['product_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('selling_history_user_id_fkey', 'selling_history', type_='foreignkey')
    op.drop_constraint('selling_history_product_id_fkey', 'selling_history', type_='foreignkey')
    op.create_foreign_key(None, 'selling_history', 'user_seller', ['user_id'], ['user_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'selling_history', 'trace_inventory', ['product_id'], ['product_id'], source_schema='public', referent_schema='public')
    op.add_column('trace_inventory', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True))
    op.drop_column('trace_inventory', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace_inventory', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('trace_inventory', 'updated_at')
    op.drop_constraint(None, 'selling_history', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'selling_history', schema='public', type_='foreignkey')
    op.create_foreign_key('selling_history_product_id_fkey', 'selling_history', 'trace_inventory', ['product_id'], ['product_id'])
    op.create_foreign_key('selling_history_user_id_fkey', 'selling_history', 'user_seller', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'buying_history', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'buying_history', schema='public', type_='foreignkey')
    op.create_foreign_key('buying_history_product_id_fkey', 'buying_history', 'trace_inventory', ['product_id'], ['product_id'])
    op.create_foreign_key('buying_history_user_id_fkey', 'buying_history', 'user_buyer', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
