"""dropping user_buyer table

Revision ID: ecfe7815b679
Revises: f7306ba859c2
Create Date: 2024-10-05 02:59:02.046714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecfe7815b679'
down_revision: Union[str, None] = 'f7306ba859c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_buyer_pkey', 'user_buyer', type_='foreignkey')   
    op.drop_table('user_buyer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_buyer',
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_buyer_pkey')
    )
    # ### end Alembic commands ###
