from alembic import op

"""removing user_buyer, user_seller, user_store_manager table and changing user-admin table name to users table

Revision ID: f7306ba859c2
Revises: aca530597653
Create Date: 2024-10-05 02:10:50.503564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7306ba859c2'
down_revision: Union[str, None] = 'aca530597653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='public'
    )
    
    op.drop_constraint('buying_history_user_id_fkey', 'buying_history', type_='foreignkey')
    op.drop_constraint('buying_history_product_id_fkey', 'buying_history', type_='foreignkey')
    op.create_foreign_key(None, 'buying_history', 'trace_inventory', ['product_id'], ['product_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'buying_history', 'users', ['user_id'], ['user_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('selling_history_user_id_fkey', 'selling_history', type_='foreignkey')
    op.drop_constraint('selling_history_product_id_fkey', 'selling_history', type_='foreignkey')
    op.create_foreign_key(None, 'selling_history', 'trace_inventory', ['product_id'], ['product_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'selling_history', 'users', ['user_id'], ['user_id'], source_schema='public', referent_schema='public')
    op.execute('DROP TABLE user_seller CASCADE;') 
    # op.execute('ALTER TABLE selling_history DROP CONSTRAINT selling_history.user_id')
    
    op.drop_constraint('selling_history_pkey', 'selling_history', type_='foreignkey')   
    op.drop_table('user_admin')
    op.drop_table('user_inventory_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'selling_history', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'selling_history', schema='public', type_='foreignkey')
    op.create_foreign_key('selling_history_product_id_fkey', 'selling_history', 'trace_inventory', ['product_id'], ['product_id'])
    op.create_foreign_key('selling_history_user_id_fkey', 'selling_history', 'user_seller', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'buying_history', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'buying_history', schema='public', type_='foreignkey')
    op.create_foreign_key('buying_history_product_id_fkey', 'buying_history', 'trace_inventory', ['product_id'], ['product_id'])
    op.create_foreign_key('buying_history_user_id_fkey', 'buying_history', 'user_buyer', ['user_id'], ['user_id'])
    op.create_table('user_inventory_manager',
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_inventory_manager_pkey')
    )
    op.create_table('user_admin',
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_admin_pkey')
    )
    op.create_table('user_buyer',
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_buyer_pkey')
    )
    op.create_table('user_seller',
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_seller_pkey')
    )
    op.drop_table('users', schema='public')
    # ### end Alembic commands ###
